### ISSUE TITLE
Network Error (Access Control Checks) in production (not localhost)

### ISSUE THREAD

**Issue by maejml** [farshed/genius-lyrics-api#11]
Hey, first of all thanks for this cool api 😄 , it's a shame we can't get the lyrics directly from genius 😒

I'm getting this **Network Error** while accessing the api in production :
`XMLHttpRequest cannot load http://api.genius.com/songs/3977187 due to access control checks.`

I tested on a browser with disabled web security, and it still doesn't work BUT there is another error :
`Mixed Content: The page at 'https://myapp.com/lyrics' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.genius.com/songs/333387'. This request has been blocked; the content must be served over HTTPS.`

So I don't really know how to fix this...
Any ideas ?

**Comment by farshed** [comment]
Hey, I just pushed a patch that should resolve these errors. Do let me know if it doesn't work.

**Comment by maejml** [comment]
Thank you for the quick reply. It now works on the browser with disabled security but still not on a normal browser...

**Comment by farshed** [comment]
`cannot load XXXXX due to access control checks` is actually a CORS error. It's probably being caused by your production or testing environment. Can you share some details about where are you hosting the app, which browser are you testing on and maybe a code snippet where you call the API?

**Comment by maejml** [comment]
My app is hosted at http://musyrics.herokuapp.com and I even registered an API client with this url at [Genius's API client management page](https://genius.com/api-clients) (so that perhaps my url is added to the allowed hosts).
I have tested on both Safari and Chrome. Here is how I call the api :
```JavaScript
import { getSongById } from "genius-lyrics-api";

export function getSongLyrics(artist, song, songId) {
    const options = {
        apiKey: process.env.REACT_APP_API_KEY_GENIUS,
        id: songId,
    };

    store.dispatch(setLoading(true));

    getSongById(options.id, options.apiKey)
        .then((song) => {
            const lyrics = song.lyrics ? song.lyrics : "Oh no! No lyrics for this song...";
            store.dispatch(setLyrics(lyrics));
            const cover = song.albumArt
                ? song.albumArt
                : "https://i.pinimg.com/originals/9f/f1/92/9ff19223638eda333d18337ac91fb9b9.gif";
            store.dispatch(setCover(cover));
            store.dispatch(setLoading(false));
        })
        .catch((error) => {
            console.error(error);
            store.dispatch(
                setLyrics("Problem fetching lyrics.")
            );
            store.dispatch(
                setCover(
                    "https://i.pinimg.com/originals/9f/f1/92/9ff19223638eda333d18337ac91fb9b9.gif"
                )
            );
            store.dispatch(setLoading(false));
        });
}
```

**Comment by mizanxali** [comment]
I tried deploying my app on Github Pages as well as Heroku. Same error in both. Is this going to be fixed anytime soon or do I have to find another lyrics scraper?

**Comment by iae1** [comment]
I have the same error for me as well.

**Comment by namirsab** [comment]
Hey everyone, it seems the problem is using the `Authorization` header. If you use the `access_token` in the query string, then there are not CORS issues. This seems to be on genius side.

One suggestion would be to expose a configuration flag that allows to configure the way authorization is done, e.g:

```js
const options = {
	apiKey: 'XXXXXXXXXXXXXXXXXXXXXXX',
	title: 'Blinding Lights',
	artist: 'The Weeknd',
	optimizeQuery: true,
        authMethod: "header" // or "queryString"
};
```

**Comment by Kalud-Z** [comment]
@namirsab Does that mean , for the time being ,we can't really use this package in production mode ?

**Comment by farshed** [comment]
An `authHeader` [boolean] property can now be passed in the configuration object. Authentication via query string is the default. Sorry this took so long.
